export const DefaultTileRegistry = {
	tiles: [
		{
			id: 0,
			name: 'grass 1',
			discriminator: 'spectrum.tile',
			image:
				'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAwUExURYeqHI+zHpW7H5/ELKTJLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANfCgf4AAAAJcEhZcwAADsMAAA7DAcdvqGQAAAEkSURBVCjPHVGJkcQgDHOoAHRbABJuYJk0ELb/nk7OJGGCH0mWg0JqCJPSlhga1D4SOPVJIgZITaYjgo/AElrn4lP3diK3m1HvzTl4R4p5dNy1cqKtEBtu/3bo+2JMXVyfTlOLMgsAmskRJ3QY5O2M82zSA0XHOsdSDO64W7p0lwITkbwULBDtxH6KSTWci/LPUWtOD3csoroNceunQKZTJNS1zi5asx7TtkluNGNM2BAf7vMXJcBP12uSZo0/yxoLPryW4qcxq94TAk0n9jtkvtOYaxfLsaZTUJeaPRX2sTlPkRSLAQiDWH7pQZgQL69dNmMJM39p0Fhr1OZ2ZmmQN0fXRtoxb2BkVTaP/xO+tWtV1VXCUDcBK323sLLCRtlIuJD4B7NMQCdDY3eJAAAAAElFTkSuQmCC'
		},
		{
			id: 1,
			name: 'grass 2',
			discriminator: 'spectrum.tile',
			image:
				'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAwUExURWSVAGueAG6kAHixBHu0BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPrCOpkAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAEkSURBVCjPHVGJkcQgDHOoAHRbABJuYJk0ELb/nk7OJGGCH0mWg0JqCJPSlhga1D4SOPVJIgZITaYjgo/AElrn4lP3diK3m1HvzTl4R4p5dNy1cqKtEBtu/3bo+2JMXVyfTlOLMgsAmskRJ3QY5O2M82zSA0XHOsdSDO64W7p0lwITkbwULBDtxH6KSTWci/LPUWtOD3csoroNceunQKZTJNS1zi5asx7TtkluNGNM2BAf7vMXJcBP12uSZo0/yxoLPryW4qcxq94TAk0n9jtkvtOYaxfLsaZTUJeaPRX2sTlPkRSLAQiDWH7pQZgQL69dNmMJM39p0Fhr1OZ2ZmmQN0fXRtoxb2BkVTaP/xO+tWtV1VXCUDcBK323sLLCRtlIuJD4B7NMQCdDY3eJAAAAAElFTkSuQmCC'
		},
		{
			id: 2,
			name: 'grass 3',
			discriminator: 'spectrum.tile',
			image:
				'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAwUExURZ/FKaXOKqzWKrPdNbniNgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANH9FEoAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAEkSURBVCjPHVGJkcQgDHOoAHRbABJuYJk0ELb/nk7OJGGCH0mWg0JqCJPSlhga1D4SOPVJIgZITaYjgo/AElrn4lP3diK3m1HvzTl4R4p5dNy1cqKtEBtu/3bo+2JMXVyfTlOLMgsAmskRJ3QY5O2M82zSA0XHOsdSDO64W7p0lwITkbwULBDtxH6KSTWci/LPUWtOD3csoroNceunQKZTJNS1zi5asx7TtkluNGNM2BAf7vMXJcBP12uSZo0/yxoLPryW4qcxq94TAk0n9jtkvtOYaxfLsaZTUJeaPRX2sTlPkRSLAQiDWH7pQZgQL69dNmMJM39p0Fhr1OZ2ZmmQN0fXRtoxb2BkVTaP/xO+tWtV1VXCUDcBK323sLLCRtlIuJD4B7NMQCdDY3eJAAAAAElFTkSuQmCC'
		},
		{
			id: 3,
			name: 'grass 4',
			discriminator: 'spectrum.tile',
			image:
				'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAwUExURXOEQXqLRYCSSIqcVI6gVgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFDCGuIAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAEkSURBVCjPHVGJkcQgDHOoAHRbABJuYJk0ELb/nk7OJGGCH0mWg0JqCJPSlhga1D4SOPVJIgZITaYjgo/AElrn4lP3diK3m1HvzTl4R4p5dNy1cqKtEBtu/3bo+2JMXVyfTlOLMgsAmskRJ3QY5O2M82zSA0XHOsdSDO64W7p0lwITkbwULBDtxH6KSTWci/LPUWtOD3csoroNceunQKZTJNS1zi5asx7TtkluNGNM2BAf7vMXJcBP12uSZo0/yxoLPryW4qcxq94TAk0n9jtkvtOYaxfLsaZTUJeaPRX2sTlPkRSLAQiDWH7pQZgQL69dNmMJM39p0Fhr1OZ2ZmmQN0fXRtoxb2BkVTaP/xO+tWtV1VXCUDcBK323sLLCRtlIuJD4B7NMQCdDY3eJAAAAAElFTkSuQmCC'
		},
		{
			id: 4,
			name: 'sand 1',
			discriminator: 'spectrum.tile',
			image:
				'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAwUExURcC7asrFe9nSeNHMgQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHIbXbsAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAENSURBVCjPJVGLjcUwCMPXBXCywKMTBLH/bmenqpSmgD+4gQiSNcGlN/N+7uFgvSywVKh9Au6ysxkEenELUAkijXjM0bEN7ljrlwaEnpeJMFMSaudoQGWC02pl5HNyiZTS2NhdTLFFPC3AubKalUpunXKkAUg5ihDD39URil4B1eixoZF1qrI1Gw9XphWmM3ZD9aXVbfAuzHf2gdcvW2zcYl1qiFXisI2Nz1i6AzNqW4vF4ngrl/TSRhkHI6aVjFqML925QYYCdkUCN77luwLdOvGR6ObO9HFH09KRshBPJ0YQR8a2D6UWV90G/GOuPftIAfSLVC3+TJo3ASGckYyVyG3tIJ/5rlZd5g4G/gESsCSGF48HmAAAAABJRU5ErkJggg=='
		},
		{
			id: 5,
			name: 'sand 2',
			discriminator: 'spectrum.tile',
			image:
				'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAwUExURX1sOY56QpqES6iTVwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG/6AKoAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAEpSURBVCjPHVHbAQQgCKJaIGsBxQXudP/djq6fygcgoqJW0qd1Ifo7Qdurm4b0FTcadSuUJHG7whvI7sDU57QShphtx7NJV+dV7cZkqKwU1Y0aFItaeGwoiTPqj7atREJ/GFewUxDenybCwPZ5yzEyXoBuPnk6Z4k9EcWt28cR9hDt6ZqedWhL2tzgY6+ykZQoy+BTBSOeylaNXmmp8VdxSpCm7lpdZYIaAq+DPebTZaKhZt1gxY5TgSpyC/ABzFZYAyvwMMjnYUgU7XPEl5IhNxg2DxLN75XM9n9HXLWYlMffoqiCTr4kTCaqU2yxvtkfFRfK+gI2bM+vaCI129FwW0vSTuRacxju8y2Ei9d1tcC3yaOUdnX0e5s8MuTEo2VsyC8XCEO0s4kfo0U8FZapO/4AAAAASUVORK5CYII='
		},
		{
			id: 6,
			name: 'sand 3',
			discriminator: 'spectrum.tile',
			image:
				'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAwUExUReTWd+rghO7pkfT0oQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ0WTWsAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAD4SURBVCjPRVGJEcMwCMMbIJiAegLi/XerhNNrLucYY/TF4AsNPsmVeytDITq4rgTC1IzEfPge9k8BlW2LZweGYA3neLS9I6p4unkRsHSDIJ4psQZ0hl+EIUXt4jUuoApsKqKgl9jitEOMJd4zLKTGKfIKiShReW+LRF1ChEu1DtPiNoN1yZ39VVwao6mgyqaB/VwvIbuUIpd5bNCZlNq+PpCzWgvJemKyQvkVsSrGnM/MeBenKfQ4UzD3vDqoifOEkdvdwqOJekRGYUrolxtvTmYUK7XZCvltUm0/40X7yCzxplKv62SUMGn9LJHVNSSMGEqnf6Xv6wvmhyjnijMc4wAAAABJRU5ErkJggg=='
		},
		{
			id: 7,
			name: 'sand 4',
			discriminator: 'spectrum.tile',
			image:
				'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAzSURBVEhL7c0hAgAwDIPArP//c2bqUXWcQfLa5tJszzhADpAD5AA5QA6QA+QAOUAOQPIBx/EDPZ1kg+QAAAAASUVORK5CYII='
		},
		{
			id: 8,
			name: 'brick 1',
			discriminator: 'spectrum.tile',
			image:
				'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAwUExURYEWCoweEIYpAJE1AKArI6A6MKo4NKpJRc6fX+7NeQAAAAAAAAAAAAAAAAAAAAAAAGLQpgMAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAD5SURBVCjPbdHRcYMwDAbgnw1gBXsDs4LPG+hYgNMGnF8JIam7Qbptf9mEkrvqBfRZGEtGXkT2WCM9ZMrI+YTYgBVPJjofwJyQksFXzido0gOYy656gZyXPanGBgsK46e0sCfWYejRDcPmg3N+HP/AtTCosTlfBWtdv1TcKgB3Foyj7QGGAVeD86EBGvA3DscZvl/lVV8QeeyV21jVHlP8gCfPD7ahN6DruTObnKFWYdlgn6haxbx2TDuDGA/o8T8kwnUedhLcrQG2YePjwOQD5ITgg82T1zJhcyNb8uEx8UImDtnAGUgFwXtSFWSqEBrYtYvgeiellPILWFKXSVkpswMAAAAASUVORK5CYII='
		},
		{
			id: 9,
			name: 'brick 2',
			discriminator: 'spectrum.tile',
			image:
				'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAwUExURaCeqLm5ucvLy9nZ3QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHdBxVYAAAAJcEhZcwAADsMAAA7DAcdvqGQAAACvSURBVCjPhZCBDcMwCAQ/YQHiLtDABs/+uxWTuHJrVUWySF6POT8ia/eo2vN0gY/rv3o5biFkOOTLMUbKud7BcNsj1zhNwgi0TdGgOLJvp+K+sBh6YZ4vwSeGGGAfjkWYoUoQd7NkEUY2Gmp/y/2tXSzTBsqvPH6/1uNfhCWYhwsZZOaRM4Dm7kOv0/jEnQNHX98yPnw4ZGKYhWXkDYeeg2UmYm4JU3mcm3aGnovqC41MUkmuOBKhAAAAAElFTkSuQmCC'
		},
		{
			id: 10,
			name: 'brick 3',
			discriminator: 'spectrum.tile',
			image:
				'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAwUExURVVPOl9YOmtjQXVtSn9ybpSFgQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM98sVsAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAEGSURBVCjPbZHRjcMwDEOZDURPUCkbuAsc4nSBoPvPUlJBgftoDVSKLZnPFNbcq/aK9SxngWMMcjBWciQZuIpZROggmQkc1NdGXBmbljYytK3WUhKbK9y5xUEVQHf84f59I96n13m+9eeIWWbYq6NIQCmswZIYVrUkGs75VSNBaUjSjDpIwksVYgsdqK+TYUZFl/1n6Ph+fRleN8d6TqnPZnnaj1WVSccMC+i1zPEQg1jSd1z2yc8XQg7DMBgCPEQZbczAA9qzc7bjlx+3fvOYQ0bE2sXiOOeEZiI/yqOxUsF3awTcMkNw0u5nZ9McYZDbDzXCUzSJxujBoGfDH370XJpFtrzODzWQOq/L1O2AAAAAAElFTkSuQmCC'
		},
		{
			id: 11,
			name: 'brick 4',
			discriminator: 'spectrum.tile',
			image:
				'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAwUExURUM2NlNPVI6BdJuOf7eqkQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEb6/MkAAAAJcEhZcwAADsMAAA7DAcdvqGQAAACPSURBVCjPjZHRDQMxCEM9QiWYICMcbAD7z3QNOar4epXKjyMLCfsFGekWoRn1UFjNoa3/G9KKsUZb25BWXPP6qEdUilya4BtmbEgb8mtjGnx0DFCsadxSABXBrXjE+wGltnZA7oZS/ccN5jEgzGN0hE4CXDTcfdJIB1ertnv5Zej+Fd8b+5/UWcazeGw0gBNVtU4gdaRFawAAAABJRU5ErkJggg=='
		},
		{
			id: 12,
			name: 'tile 1',
			discriminator: 'spectrum.tile',
			image:
				'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAwUExURVNPVF5aYG1pcHd0fH15f4aDjJOQmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANBjv34AAAAJcEhZcwAADsMAAA7DAcdvqGQAAACtSURBVCjPjZHRDcMwCEQ9QkeIWMGC/0aZgRHYf4TeYbu203wUIWOdAo+Ly6vc4pQtjnJ6yJIQVIXpUg0JwUSQEFgoaN5qK3rkUGsDWZ4Ej3CMjxDDwRkV/TjAqIPSAFkbZQqd4sEtMGVQlFtwyvBi/IhNzYvP1dWfBPR/vdThhYBEdUoCEpWUdTG/r55CN5qWk9KNpuU//5hML4OyP4ORQQHp3cuSx+9jX1tc7w81RGCsS/KB3wAAAABJRU5ErkJggg=='
		},
		{
			id: 13,
			name: 'tile 2',
			discriminator: 'spectrum.tile',
			image:
				'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAwUExURS9JXj5hfEZdb0p1l1NyilSEqmeRswAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI6bffYAAAAJcEhZcwAADsMAAA7DAcdvqGQAAACtSURBVCjPjZHRDcMwCEQ9gtmgO1jwnyozMAL7j9A7bDd2mo8iZKxT4HFxeZVbHLJFLYeHLAlBVZguzZAQTAQJgYWC5q31ojWHWh/I8iR4hGN8hBgOzmjoxwFGm5QOyNoplzAoHtwCUyZFuQWnTC/Gj9jUvfi1uvqTgP6vlza9EJCoQUlAopKyLub31VMYRtNyUobRtPznH5PLy6Tsz2BkUED68LJk/X3sc4vz/QEvNk+bal6S+gAAAABJRU5ErkJggg=='
		},
		{
			id: 14,
			name: 'tile 3',
			discriminator: 'spectrum.tile',
			image:
				'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAwUExURUM2Nkw+PlFCQlZGRlpLSwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAawlkAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABUSURBVCjPY8AALkDgYAwCBmAmlQQckG0ACygBgQKYIE4ACBACIB7QdIQAkAMRUIAoRBIQFBQUIEUAqB8kALGBTDOwuAPZpRh+ISM8sIQptWPOxQEAM0FUsD6ViQoAAAAASUVORK5CYII='
		},
		{
			id: 15,
			name: 'boards 1',
			discriminator: 'spectrum.tile',
			image:
				'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB4AAAAgCAIAAACKIl8oAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABNSURBVEhLY9y6qICBNoBxTksIlEltwASlaQBGjUYDNDSaMdnPGsqkNhhN12hg1Gg0MJqu0cBoukYDo0ajgdF0jQZGUwgaGE3XKICBAQD34RDRGxBJAgAAAABJRU5ErkJggg=='
		}
	]
};
